DROP TABLE IF EXISTS ida_banners;
DROP TABLE IF EXISTS ida_contacts;
DROP TABLE IF EXISTS ida_images;
DROP TABLE IF EXISTS ida_integration_properties;
DROP TABLE IF EXISTS ida_last_updates;
DROP TABLE IF EXISTS ida_properties;
DROP TABLE IF EXISTS ida_users;
DROP TABLE IF EXISTS ida_job_statuses;
DROP TABLE IF EXISTS ida_offices;
DROP TABLE IF EXISTS ida_atms;
DROP TABLE IF EXISTS ida_email_conf;

-- HomeCredit: custom
DROP TABLE IF EXISTS ida_hc_product_types;
DROP TABLE IF EXISTS ida_hc_statuses;
DROP TABLE IF EXISTS idb_hc_offices;
DROP TABLE IF EXISTS idb_hc_atms;
DROP TABLE IF EXISTS ida_hc_beneficiaries;
DROP TABLE IF EXISTS ida_hc_payment_categories;

DROP TABLE IF EXISTS IDB_HC_PARTNERS;
DROP TABLE IF EXISTS IDB_HC_SHOPS;

DROP TABLE IF EXISTS IDA_HC_SHOPS;
DROP TABLE IF EXISTS IDA_HC_PARTNERS;
DROP TABLE IF EXISTS IDA_HC_DISCOUNT_CATEGORIES;

DROP SEQUENCE IF EXISTS hibernate_sequence;