--
-- Table structure for table IDA_HC_DISCOUNT_CATEGORIES
--

CREATE TABLE	IDA_HC_DISCOUNT_CATEGORIES (
	CATEGORY_ID		INT NOT NULL DEFAULT NEXTVAL('hibernate_sequence'),
	CATEGORY_NAME	VARCHAR(255) DEFAULT NULL,
	IMAGE_ID		VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY (CATEGORY_ID)
);

--
-- Table structure for table IDA_HC_PARTNERS
--

CREATE TABLE	IDA_HC_PARTNERS (
	PARTNER_ID		BIGINT NOT NULL,
	TITLE			VARCHAR(255),
	PHONE_NUMBER	VARCHAR(255),
	URL				VARCHAR(255),
	LOGO_URL		VARCHAR(255),
	CATEGORY_ID		INT NOT NULL,
	PRIMARY KEY (PARTNER_ID)
);

--
-- Table structure for table IDA_HC_PARTNERS
--

CREATE TABLE	IDA_HC_SHOPS (
	SHOP_ID			BIGINT NOT NULL,
	NAME			VARCHAR(255),
	CITY			VARCHAR(255),
	ADDRESS			VARCHAR(2024),
	LATITUDE		DECIMAL(10, 7),
	LONGITUDE		DECIMAL(10, 7),
	DISCOUNT		VARCHAR(512),
	DESCRIPTION		VARCHAR(4000),
	PARTNER_ID		INT NOT NULL,
	PRIMARY KEY (SHOP_ID)
);

