 INSERT INTO IDA_HC_DISCOUNT_CATEGORIES(CATEGORY_ID, CATEGORY_NAME, IMAGE_ID) 
 VALUES (1, 'Мебель и товары для дома', NULL);
 
 INSERT INTO IDA_HC_DISCOUNT_CATEGORIES(CATEGORY_ID, CATEGORY_NAME, IMAGE_ID) 
 VALUES (2, 'Страхование', NULL);
 
 INSERT INTO IDA_HC_DISCOUNT_CATEGORIES(CATEGORY_ID, CATEGORY_NAME, IMAGE_ID) 
 VALUES (3, 'Бытовая техника и электроника', NULL);
 
 INSERT INTO IDA_HC_DISCOUNT_CATEGORIES(CATEGORY_ID, CATEGORY_NAME, IMAGE_ID) 
 VALUES (4, 'Товары для детей', NULL);
 
 INSERT INTO IDA_HC_DISCOUNT_CATEGORIES(CATEGORY_ID, CATEGORY_NAME, IMAGE_ID) 
 VALUES (5, 'Мобильные телефоны', NULL);
 
 INSERT INTO IDA_HC_DISCOUNT_CATEGORIES(CATEGORY_ID, CATEGORY_NAME, IMAGE_ID) 
 VALUES (6, 'Ювелирные украшения', NULL);
 
 INSERT INTO IDA_HC_DISCOUNT_CATEGORIES(CATEGORY_ID, CATEGORY_NAME, IMAGE_ID) 
 VALUES (7, 'Другое', NULL);
 
 INSERT INTO IDA_HC_DISCOUNT_CATEGORIES(CATEGORY_ID, CATEGORY_NAME, IMAGE_ID) 
 VALUES (8, 'Подарки', NULL);
 
 INSERT INTO IDA_HC_DISCOUNT_CATEGORIES(CATEGORY_ID, CATEGORY_NAME, IMAGE_ID) 
 VALUES (9, 'Аптеки', NULL);
 
 INSERT INTO IDA_HC_DISCOUNT_CATEGORIES(CATEGORY_ID, CATEGORY_NAME, IMAGE_ID) 
 VALUES (10, 'Строительные материалы', NULL);
 
 INSERT INTO IDA_HC_DISCOUNT_CATEGORIES(CATEGORY_ID, CATEGORY_NAME, IMAGE_ID) 
 VALUES (11, 'Продукты питания', NULL);
 
 INSERT INTO IDA_HC_DISCOUNT_CATEGORIES(CATEGORY_ID, CATEGORY_NAME, IMAGE_ID) 
 VALUES (12, 'Спорт', NULL);
 
 INSERT INTO IDA_HC_DISCOUNT_CATEGORIES(CATEGORY_ID, CATEGORY_NAME, IMAGE_ID) 
 VALUES (13, 'Образование', NULL);
 
 INSERT INTO IDA_HC_DISCOUNT_CATEGORIES(CATEGORY_ID, CATEGORY_NAME, IMAGE_ID) 
 VALUES (14, 'Парфюмерия и косметика', NULL);
 
 INSERT INTO IDA_HC_DISCOUNT_CATEGORIES(CATEGORY_ID, CATEGORY_NAME, IMAGE_ID) 
 VALUES (15, 'Красота и здоровье', NULL);
 
 INSERT INTO IDA_HC_DISCOUNT_CATEGORIES(CATEGORY_ID, CATEGORY_NAME, IMAGE_ID) 
 VALUES (16, 'Одежда, обувь, аксессуары', NULL);
 
 INSERT INTO IDA_HC_DISCOUNT_CATEGORIES(CATEGORY_ID, CATEGORY_NAME, IMAGE_ID) 
 VALUES (17, 'Рестораны и кафе', NULL);
 
 INSERT INTO IDA_HC_DISCOUNT_CATEGORIES(CATEGORY_ID, CATEGORY_NAME, IMAGE_ID) 
 VALUES (18, 'Профессиональные услуги', NULL);
 
 INSERT INTO IDA_HC_DISCOUNT_CATEGORIES(CATEGORY_ID, CATEGORY_NAME, IMAGE_ID) 
 VALUES (19, 'Покупки через Интернет', NULL);
 
 INSERT INTO IDA_HC_DISCOUNT_CATEGORIES(CATEGORY_ID, CATEGORY_NAME, IMAGE_ID) 
 VALUES (20, 'Выгодный маршрут', NULL);
 
 INSERT INTO IDA_HC_DISCOUNT_CATEGORIES(CATEGORY_ID, CATEGORY_NAME, IMAGE_ID) 
 VALUES (21, 'Туризм и отдых', NULL);
 
 INSERT INTO IDA_HC_DISCOUNT_CATEGORIES(CATEGORY_ID, CATEGORY_NAME, IMAGE_ID) 
 VALUES (22, 'Автомобили и Мотоциклы', NULL);
 
 INSERT INTO IDA_HC_DISCOUNT_CATEGORIES(CATEGORY_ID, CATEGORY_NAME, IMAGE_ID) 
 VALUES (23, 'АЗС', NULL);
