// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: banners.proto

package com.idamobile.protocol.ubrr;

public final class Banners {
  private Banners() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BannerMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 orderNumber = 1;
    boolean hasOrderNumber();
    int getOrderNumber();
    
    // optional string imageId = 2;
    boolean hasImageId();
    String getImageId();
    
    // optional string title = 3;
    boolean hasTitle();
    String getTitle();
    
    // optional string text = 4;
    boolean hasText();
    String getText();
    
    // optional string url = 5;
    boolean hasUrl();
    String getUrl();
  }
  public static final class BannerMessage extends
      com.google.protobuf.GeneratedMessage
      implements BannerMessageOrBuilder {
    // Use BannerMessage.newBuilder() to construct.
    private BannerMessage(Builder builder) {
      super(builder);
    }
    private BannerMessage(boolean noInit) {}
    
    private static final BannerMessage defaultInstance;
    public static BannerMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public BannerMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.idamobile.protocol.ubrr.Banners.internal_static_messaging_BannerMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.idamobile.protocol.ubrr.Banners.internal_static_messaging_BannerMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 orderNumber = 1;
    public static final int ORDERNUMBER_FIELD_NUMBER = 1;
    private int orderNumber_;
    public boolean hasOrderNumber() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getOrderNumber() {
      return orderNumber_;
    }
    
    // optional string imageId = 2;
    public static final int IMAGEID_FIELD_NUMBER = 2;
    private java.lang.Object imageId_;
    public boolean hasImageId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getImageId() {
      java.lang.Object ref = imageId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          imageId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getImageIdBytes() {
      java.lang.Object ref = imageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        imageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string title = 3;
    public static final int TITLE_FIELD_NUMBER = 3;
    private java.lang.Object title_;
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          title_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string text = 4;
    public static final int TEXT_FIELD_NUMBER = 4;
    private java.lang.Object text_;
    public boolean hasText() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          text_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string url = 5;
    public static final int URL_FIELD_NUMBER = 5;
    private java.lang.Object url_;
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          url_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      orderNumber_ = 0;
      imageId_ = "";
      title_ = "";
      text_ = "";
      url_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasOrderNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, orderNumber_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getImageIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTitleBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTextBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getUrlBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, orderNumber_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getImageIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTitleBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTextBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getUrlBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.idamobile.protocol.ubrr.Banners.BannerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Banners.BannerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Banners.BannerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Banners.BannerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Banners.BannerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Banners.BannerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Banners.BannerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.idamobile.protocol.ubrr.Banners.BannerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.idamobile.protocol.ubrr.Banners.BannerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Banners.BannerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.idamobile.protocol.ubrr.Banners.BannerMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.idamobile.protocol.ubrr.Banners.BannerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.idamobile.protocol.ubrr.Banners.internal_static_messaging_BannerMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.idamobile.protocol.ubrr.Banners.internal_static_messaging_BannerMessage_fieldAccessorTable;
      }
      
      // Construct using com.idamobile.protocol.ubrr.Banners.BannerMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        orderNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        imageId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.idamobile.protocol.ubrr.Banners.BannerMessage.getDescriptor();
      }
      
      public com.idamobile.protocol.ubrr.Banners.BannerMessage getDefaultInstanceForType() {
        return com.idamobile.protocol.ubrr.Banners.BannerMessage.getDefaultInstance();
      }
      
      public com.idamobile.protocol.ubrr.Banners.BannerMessage build() {
        com.idamobile.protocol.ubrr.Banners.BannerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.idamobile.protocol.ubrr.Banners.BannerMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.idamobile.protocol.ubrr.Banners.BannerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.idamobile.protocol.ubrr.Banners.BannerMessage buildPartial() {
        com.idamobile.protocol.ubrr.Banners.BannerMessage result = new com.idamobile.protocol.ubrr.Banners.BannerMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.orderNumber_ = orderNumber_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.imageId_ = imageId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.text_ = text_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.url_ = url_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.idamobile.protocol.ubrr.Banners.BannerMessage) {
          return mergeFrom((com.idamobile.protocol.ubrr.Banners.BannerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.idamobile.protocol.ubrr.Banners.BannerMessage other) {
        if (other == com.idamobile.protocol.ubrr.Banners.BannerMessage.getDefaultInstance()) return this;
        if (other.hasOrderNumber()) {
          setOrderNumber(other.getOrderNumber());
        }
        if (other.hasImageId()) {
          setImageId(other.getImageId());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasText()) {
          setText(other.getText());
        }
        if (other.hasUrl()) {
          setUrl(other.getUrl());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasOrderNumber()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              orderNumber_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              imageId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              title_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              text_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              url_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 orderNumber = 1;
      private int orderNumber_ ;
      public boolean hasOrderNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getOrderNumber() {
        return orderNumber_;
      }
      public Builder setOrderNumber(int value) {
        bitField0_ |= 0x00000001;
        orderNumber_ = value;
        onChanged();
        return this;
      }
      public Builder clearOrderNumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        orderNumber_ = 0;
        onChanged();
        return this;
      }
      
      // optional string imageId = 2;
      private java.lang.Object imageId_ = "";
      public boolean hasImageId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getImageId() {
        java.lang.Object ref = imageId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          imageId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setImageId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        imageId_ = value;
        onChanged();
        return this;
      }
      public Builder clearImageId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        imageId_ = getDefaultInstance().getImageId();
        onChanged();
        return this;
      }
      void setImageId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        imageId_ = value;
        onChanged();
      }
      
      // optional string title = 3;
      private java.lang.Object title_ = "";
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTitle(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        title_ = value;
        onChanged();
        return this;
      }
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000004);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      void setTitle(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        title_ = value;
        onChanged();
      }
      
      // optional string text = 4;
      private java.lang.Object text_ = "";
      public boolean hasText() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setText(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        text_ = value;
        onChanged();
        return this;
      }
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000008);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      void setText(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        text_ = value;
        onChanged();
      }
      
      // optional string url = 5;
      private java.lang.Object url_ = "";
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUrl(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        url_ = value;
        onChanged();
        return this;
      }
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000010);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      void setUrl(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        url_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:messaging.BannerMessage)
    }
    
    static {
      defaultInstance = new BannerMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:messaging.BannerMessage)
  }
  
  public interface BannersRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int64 lastUpdateTime = 1;
    boolean hasLastUpdateTime();
    long getLastUpdateTime();
  }
  public static final class BannersRequest extends
      com.google.protobuf.GeneratedMessage
      implements BannersRequestOrBuilder {
    // Use BannersRequest.newBuilder() to construct.
    private BannersRequest(Builder builder) {
      super(builder);
    }
    private BannersRequest(boolean noInit) {}
    
    private static final BannersRequest defaultInstance;
    public static BannersRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public BannersRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.idamobile.protocol.ubrr.Banners.internal_static_messaging_BannersRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.idamobile.protocol.ubrr.Banners.internal_static_messaging_BannersRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int64 lastUpdateTime = 1;
    public static final int LASTUPDATETIME_FIELD_NUMBER = 1;
    private long lastUpdateTime_;
    public boolean hasLastUpdateTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getLastUpdateTime() {
      return lastUpdateTime_;
    }
    
    private void initFields() {
      lastUpdateTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, lastUpdateTime_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, lastUpdateTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.idamobile.protocol.ubrr.Banners.BannersRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Banners.BannersRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Banners.BannersRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Banners.BannersRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Banners.BannersRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Banners.BannersRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Banners.BannersRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.idamobile.protocol.ubrr.Banners.BannersRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.idamobile.protocol.ubrr.Banners.BannersRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Banners.BannersRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.idamobile.protocol.ubrr.Banners.BannersRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.idamobile.protocol.ubrr.Banners.BannersRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.idamobile.protocol.ubrr.Banners.internal_static_messaging_BannersRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.idamobile.protocol.ubrr.Banners.internal_static_messaging_BannersRequest_fieldAccessorTable;
      }
      
      // Construct using com.idamobile.protocol.ubrr.Banners.BannersRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        lastUpdateTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.idamobile.protocol.ubrr.Banners.BannersRequest.getDescriptor();
      }
      
      public com.idamobile.protocol.ubrr.Banners.BannersRequest getDefaultInstanceForType() {
        return com.idamobile.protocol.ubrr.Banners.BannersRequest.getDefaultInstance();
      }
      
      public com.idamobile.protocol.ubrr.Banners.BannersRequest build() {
        com.idamobile.protocol.ubrr.Banners.BannersRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.idamobile.protocol.ubrr.Banners.BannersRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.idamobile.protocol.ubrr.Banners.BannersRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.idamobile.protocol.ubrr.Banners.BannersRequest buildPartial() {
        com.idamobile.protocol.ubrr.Banners.BannersRequest result = new com.idamobile.protocol.ubrr.Banners.BannersRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.lastUpdateTime_ = lastUpdateTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.idamobile.protocol.ubrr.Banners.BannersRequest) {
          return mergeFrom((com.idamobile.protocol.ubrr.Banners.BannersRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.idamobile.protocol.ubrr.Banners.BannersRequest other) {
        if (other == com.idamobile.protocol.ubrr.Banners.BannersRequest.getDefaultInstance()) return this;
        if (other.hasLastUpdateTime()) {
          setLastUpdateTime(other.getLastUpdateTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              lastUpdateTime_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 lastUpdateTime = 1;
      private long lastUpdateTime_ ;
      public boolean hasLastUpdateTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getLastUpdateTime() {
        return lastUpdateTime_;
      }
      public Builder setLastUpdateTime(long value) {
        bitField0_ |= 0x00000001;
        lastUpdateTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearLastUpdateTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        lastUpdateTime_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:messaging.BannersRequest)
    }
    
    static {
      defaultInstance = new BannersRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:messaging.BannersRequest)
  }
  
  public interface BannersResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 lastUpdateTime = 1;
    boolean hasLastUpdateTime();
    long getLastUpdateTime();
    
    // repeated .messaging.BannerMessage banners = 2;
    java.util.List<com.idamobile.protocol.ubrr.Banners.BannerMessage> 
        getBannersList();
    com.idamobile.protocol.ubrr.Banners.BannerMessage getBanners(int index);
    int getBannersCount();
    java.util.List<? extends com.idamobile.protocol.ubrr.Banners.BannerMessageOrBuilder> 
        getBannersOrBuilderList();
    com.idamobile.protocol.ubrr.Banners.BannerMessageOrBuilder getBannersOrBuilder(
        int index);
  }
  public static final class BannersResponse extends
      com.google.protobuf.GeneratedMessage
      implements BannersResponseOrBuilder {
    // Use BannersResponse.newBuilder() to construct.
    private BannersResponse(Builder builder) {
      super(builder);
    }
    private BannersResponse(boolean noInit) {}
    
    private static final BannersResponse defaultInstance;
    public static BannersResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public BannersResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.idamobile.protocol.ubrr.Banners.internal_static_messaging_BannersResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.idamobile.protocol.ubrr.Banners.internal_static_messaging_BannersResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int64 lastUpdateTime = 1;
    public static final int LASTUPDATETIME_FIELD_NUMBER = 1;
    private long lastUpdateTime_;
    public boolean hasLastUpdateTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getLastUpdateTime() {
      return lastUpdateTime_;
    }
    
    // repeated .messaging.BannerMessage banners = 2;
    public static final int BANNERS_FIELD_NUMBER = 2;
    private java.util.List<com.idamobile.protocol.ubrr.Banners.BannerMessage> banners_;
    public java.util.List<com.idamobile.protocol.ubrr.Banners.BannerMessage> getBannersList() {
      return banners_;
    }
    public java.util.List<? extends com.idamobile.protocol.ubrr.Banners.BannerMessageOrBuilder> 
        getBannersOrBuilderList() {
      return banners_;
    }
    public int getBannersCount() {
      return banners_.size();
    }
    public com.idamobile.protocol.ubrr.Banners.BannerMessage getBanners(int index) {
      return banners_.get(index);
    }
    public com.idamobile.protocol.ubrr.Banners.BannerMessageOrBuilder getBannersOrBuilder(
        int index) {
      return banners_.get(index);
    }
    
    private void initFields() {
      lastUpdateTime_ = 0L;
      banners_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasLastUpdateTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getBannersCount(); i++) {
        if (!getBanners(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, lastUpdateTime_);
      }
      for (int i = 0; i < banners_.size(); i++) {
        output.writeMessage(2, banners_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, lastUpdateTime_);
      }
      for (int i = 0; i < banners_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, banners_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.idamobile.protocol.ubrr.Banners.BannersResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Banners.BannersResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Banners.BannersResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Banners.BannersResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Banners.BannersResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Banners.BannersResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Banners.BannersResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.idamobile.protocol.ubrr.Banners.BannersResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.idamobile.protocol.ubrr.Banners.BannersResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Banners.BannersResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.idamobile.protocol.ubrr.Banners.BannersResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.idamobile.protocol.ubrr.Banners.BannersResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.idamobile.protocol.ubrr.Banners.internal_static_messaging_BannersResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.idamobile.protocol.ubrr.Banners.internal_static_messaging_BannersResponse_fieldAccessorTable;
      }
      
      // Construct using com.idamobile.protocol.ubrr.Banners.BannersResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBannersFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        lastUpdateTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (bannersBuilder_ == null) {
          banners_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          bannersBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.idamobile.protocol.ubrr.Banners.BannersResponse.getDescriptor();
      }
      
      public com.idamobile.protocol.ubrr.Banners.BannersResponse getDefaultInstanceForType() {
        return com.idamobile.protocol.ubrr.Banners.BannersResponse.getDefaultInstance();
      }
      
      public com.idamobile.protocol.ubrr.Banners.BannersResponse build() {
        com.idamobile.protocol.ubrr.Banners.BannersResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.idamobile.protocol.ubrr.Banners.BannersResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.idamobile.protocol.ubrr.Banners.BannersResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.idamobile.protocol.ubrr.Banners.BannersResponse buildPartial() {
        com.idamobile.protocol.ubrr.Banners.BannersResponse result = new com.idamobile.protocol.ubrr.Banners.BannersResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.lastUpdateTime_ = lastUpdateTime_;
        if (bannersBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            banners_ = java.util.Collections.unmodifiableList(banners_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.banners_ = banners_;
        } else {
          result.banners_ = bannersBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.idamobile.protocol.ubrr.Banners.BannersResponse) {
          return mergeFrom((com.idamobile.protocol.ubrr.Banners.BannersResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.idamobile.protocol.ubrr.Banners.BannersResponse other) {
        if (other == com.idamobile.protocol.ubrr.Banners.BannersResponse.getDefaultInstance()) return this;
        if (other.hasLastUpdateTime()) {
          setLastUpdateTime(other.getLastUpdateTime());
        }
        if (bannersBuilder_ == null) {
          if (!other.banners_.isEmpty()) {
            if (banners_.isEmpty()) {
              banners_ = other.banners_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureBannersIsMutable();
              banners_.addAll(other.banners_);
            }
            onChanged();
          }
        } else {
          if (!other.banners_.isEmpty()) {
            if (bannersBuilder_.isEmpty()) {
              bannersBuilder_.dispose();
              bannersBuilder_ = null;
              banners_ = other.banners_;
              bitField0_ = (bitField0_ & ~0x00000002);
              bannersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBannersFieldBuilder() : null;
            } else {
              bannersBuilder_.addAllMessages(other.banners_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasLastUpdateTime()) {
          
          return false;
        }
        for (int i = 0; i < getBannersCount(); i++) {
          if (!getBanners(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              lastUpdateTime_ = input.readInt64();
              break;
            }
            case 18: {
              com.idamobile.protocol.ubrr.Banners.BannerMessage.Builder subBuilder = com.idamobile.protocol.ubrr.Banners.BannerMessage.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addBanners(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 lastUpdateTime = 1;
      private long lastUpdateTime_ ;
      public boolean hasLastUpdateTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getLastUpdateTime() {
        return lastUpdateTime_;
      }
      public Builder setLastUpdateTime(long value) {
        bitField0_ |= 0x00000001;
        lastUpdateTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearLastUpdateTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        lastUpdateTime_ = 0L;
        onChanged();
        return this;
      }
      
      // repeated .messaging.BannerMessage banners = 2;
      private java.util.List<com.idamobile.protocol.ubrr.Banners.BannerMessage> banners_ =
        java.util.Collections.emptyList();
      private void ensureBannersIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          banners_ = new java.util.ArrayList<com.idamobile.protocol.ubrr.Banners.BannerMessage>(banners_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.idamobile.protocol.ubrr.Banners.BannerMessage, com.idamobile.protocol.ubrr.Banners.BannerMessage.Builder, com.idamobile.protocol.ubrr.Banners.BannerMessageOrBuilder> bannersBuilder_;
      
      public java.util.List<com.idamobile.protocol.ubrr.Banners.BannerMessage> getBannersList() {
        if (bannersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(banners_);
        } else {
          return bannersBuilder_.getMessageList();
        }
      }
      public int getBannersCount() {
        if (bannersBuilder_ == null) {
          return banners_.size();
        } else {
          return bannersBuilder_.getCount();
        }
      }
      public com.idamobile.protocol.ubrr.Banners.BannerMessage getBanners(int index) {
        if (bannersBuilder_ == null) {
          return banners_.get(index);
        } else {
          return bannersBuilder_.getMessage(index);
        }
      }
      public Builder setBanners(
          int index, com.idamobile.protocol.ubrr.Banners.BannerMessage value) {
        if (bannersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBannersIsMutable();
          banners_.set(index, value);
          onChanged();
        } else {
          bannersBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setBanners(
          int index, com.idamobile.protocol.ubrr.Banners.BannerMessage.Builder builderForValue) {
        if (bannersBuilder_ == null) {
          ensureBannersIsMutable();
          banners_.set(index, builderForValue.build());
          onChanged();
        } else {
          bannersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addBanners(com.idamobile.protocol.ubrr.Banners.BannerMessage value) {
        if (bannersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBannersIsMutable();
          banners_.add(value);
          onChanged();
        } else {
          bannersBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addBanners(
          int index, com.idamobile.protocol.ubrr.Banners.BannerMessage value) {
        if (bannersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBannersIsMutable();
          banners_.add(index, value);
          onChanged();
        } else {
          bannersBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addBanners(
          com.idamobile.protocol.ubrr.Banners.BannerMessage.Builder builderForValue) {
        if (bannersBuilder_ == null) {
          ensureBannersIsMutable();
          banners_.add(builderForValue.build());
          onChanged();
        } else {
          bannersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addBanners(
          int index, com.idamobile.protocol.ubrr.Banners.BannerMessage.Builder builderForValue) {
        if (bannersBuilder_ == null) {
          ensureBannersIsMutable();
          banners_.add(index, builderForValue.build());
          onChanged();
        } else {
          bannersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllBanners(
          java.lang.Iterable<? extends com.idamobile.protocol.ubrr.Banners.BannerMessage> values) {
        if (bannersBuilder_ == null) {
          ensureBannersIsMutable();
          super.addAll(values, banners_);
          onChanged();
        } else {
          bannersBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearBanners() {
        if (bannersBuilder_ == null) {
          banners_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          bannersBuilder_.clear();
        }
        return this;
      }
      public Builder removeBanners(int index) {
        if (bannersBuilder_ == null) {
          ensureBannersIsMutable();
          banners_.remove(index);
          onChanged();
        } else {
          bannersBuilder_.remove(index);
        }
        return this;
      }
      public com.idamobile.protocol.ubrr.Banners.BannerMessage.Builder getBannersBuilder(
          int index) {
        return getBannersFieldBuilder().getBuilder(index);
      }
      public com.idamobile.protocol.ubrr.Banners.BannerMessageOrBuilder getBannersOrBuilder(
          int index) {
        if (bannersBuilder_ == null) {
          return banners_.get(index);  } else {
          return bannersBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.idamobile.protocol.ubrr.Banners.BannerMessageOrBuilder> 
           getBannersOrBuilderList() {
        if (bannersBuilder_ != null) {
          return bannersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(banners_);
        }
      }
      public com.idamobile.protocol.ubrr.Banners.BannerMessage.Builder addBannersBuilder() {
        return getBannersFieldBuilder().addBuilder(
            com.idamobile.protocol.ubrr.Banners.BannerMessage.getDefaultInstance());
      }
      public com.idamobile.protocol.ubrr.Banners.BannerMessage.Builder addBannersBuilder(
          int index) {
        return getBannersFieldBuilder().addBuilder(
            index, com.idamobile.protocol.ubrr.Banners.BannerMessage.getDefaultInstance());
      }
      public java.util.List<com.idamobile.protocol.ubrr.Banners.BannerMessage.Builder> 
           getBannersBuilderList() {
        return getBannersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.idamobile.protocol.ubrr.Banners.BannerMessage, com.idamobile.protocol.ubrr.Banners.BannerMessage.Builder, com.idamobile.protocol.ubrr.Banners.BannerMessageOrBuilder> 
          getBannersFieldBuilder() {
        if (bannersBuilder_ == null) {
          bannersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.idamobile.protocol.ubrr.Banners.BannerMessage, com.idamobile.protocol.ubrr.Banners.BannerMessage.Builder, com.idamobile.protocol.ubrr.Banners.BannerMessageOrBuilder>(
                  banners_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          banners_ = null;
        }
        return bannersBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:messaging.BannersResponse)
    }
    
    static {
      defaultInstance = new BannersResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:messaging.BannersResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messaging_BannerMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messaging_BannerMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messaging_BannersRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messaging_BannersRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messaging_BannersResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messaging_BannersResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rbanners.proto\022\tmessaging\032\rcommons.prot" +
      "o\"_\n\rBannerMessage\022\023\n\013orderNumber\030\001 \002(\005\022" +
      "\017\n\007imageId\030\002 \001(\t\022\r\n\005title\030\003 \001(\t\022\014\n\004text\030" +
      "\004 \001(\t\022\013\n\003url\030\005 \001(\t\"(\n\016BannersRequest\022\026\n\016" +
      "lastUpdateTime\030\001 \001(\003\"T\n\017BannersResponse\022" +
      "\026\n\016lastUpdateTime\030\001 \002(\003\022)\n\007banners\030\002 \003(\013" +
      "2\030.messaging.BannerMessageB\035\n\033com.idamob" +
      "ile.protocol.ubrr"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_messaging_BannerMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_messaging_BannerMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messaging_BannerMessage_descriptor,
              new java.lang.String[] { "OrderNumber", "ImageId", "Title", "Text", "Url", },
              com.idamobile.protocol.ubrr.Banners.BannerMessage.class,
              com.idamobile.protocol.ubrr.Banners.BannerMessage.Builder.class);
          internal_static_messaging_BannersRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_messaging_BannersRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messaging_BannersRequest_descriptor,
              new java.lang.String[] { "LastUpdateTime", },
              com.idamobile.protocol.ubrr.Banners.BannersRequest.class,
              com.idamobile.protocol.ubrr.Banners.BannersRequest.Builder.class);
          internal_static_messaging_BannersResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_messaging_BannersResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messaging_BannersResponse_descriptor,
              new java.lang.String[] { "LastUpdateTime", "Banners", },
              com.idamobile.protocol.ubrr.Banners.BannersResponse.class,
              com.idamobile.protocol.ubrr.Banners.BannersResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.idamobile.protocol.ubrr.Commons.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
