// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: currency.proto

package com.idamobile.protocol.ubrr;

public final class Currency {
  private Currency() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum CurrencyOperation
      implements com.google.protobuf.ProtocolMessageEnum {
    BUY(0, 0),
    SELL(1, 1),
    CENTRAL(2, 2),
    ;
    
    public static final int BUY_VALUE = 0;
    public static final int SELL_VALUE = 1;
    public static final int CENTRAL_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static CurrencyOperation valueOf(int value) {
      switch (value) {
        case 0: return BUY;
        case 1: return SELL;
        case 2: return CENTRAL;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<CurrencyOperation>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CurrencyOperation>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CurrencyOperation>() {
            public CurrencyOperation findValueByNumber(int number) {
              return CurrencyOperation.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.idamobile.protocol.ubrr.Currency.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final CurrencyOperation[] VALUES = {
      BUY, SELL, CENTRAL, 
    };
    
    public static CurrencyOperation valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private CurrencyOperation(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:messaging.CurrencyOperation)
  }
  
  public interface CurrencyMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .messaging.CurrencyOperation operation = 1;
    boolean hasOperation();
    com.idamobile.protocol.ubrr.Currency.CurrencyOperation getOperation();
    
    // required int32 currency = 2;
    boolean hasCurrency();
    int getCurrency();
    
    // required double price = 3;
    boolean hasPrice();
    double getPrice();
    
    // required double amount = 4;
    boolean hasAmount();
    double getAmount();
    
    // required double delta = 5;
    boolean hasDelta();
    double getDelta();
  }
  public static final class CurrencyMessage extends
      com.google.protobuf.GeneratedMessage
      implements CurrencyMessageOrBuilder {
    // Use CurrencyMessage.newBuilder() to construct.
    private CurrencyMessage(Builder builder) {
      super(builder);
    }
    private CurrencyMessage(boolean noInit) {}
    
    private static final CurrencyMessage defaultInstance;
    public static CurrencyMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public CurrencyMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.idamobile.protocol.ubrr.Currency.internal_static_messaging_CurrencyMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.idamobile.protocol.ubrr.Currency.internal_static_messaging_CurrencyMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .messaging.CurrencyOperation operation = 1;
    public static final int OPERATION_FIELD_NUMBER = 1;
    private com.idamobile.protocol.ubrr.Currency.CurrencyOperation operation_;
    public boolean hasOperation() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.idamobile.protocol.ubrr.Currency.CurrencyOperation getOperation() {
      return operation_;
    }
    
    // required int32 currency = 2;
    public static final int CURRENCY_FIELD_NUMBER = 2;
    private int currency_;
    public boolean hasCurrency() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getCurrency() {
      return currency_;
    }
    
    // required double price = 3;
    public static final int PRICE_FIELD_NUMBER = 3;
    private double price_;
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public double getPrice() {
      return price_;
    }
    
    // required double amount = 4;
    public static final int AMOUNT_FIELD_NUMBER = 4;
    private double amount_;
    public boolean hasAmount() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public double getAmount() {
      return amount_;
    }
    
    // required double delta = 5;
    public static final int DELTA_FIELD_NUMBER = 5;
    private double delta_;
    public boolean hasDelta() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public double getDelta() {
      return delta_;
    }
    
    private void initFields() {
      operation_ = com.idamobile.protocol.ubrr.Currency.CurrencyOperation.BUY;
      currency_ = 0;
      price_ = 0D;
      amount_ = 0D;
      delta_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasOperation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCurrency()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAmount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDelta()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, operation_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, currency_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, price_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, amount_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, delta_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, operation_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, currency_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, price_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, amount_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, delta_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.idamobile.protocol.ubrr.Currency.CurrencyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.idamobile.protocol.ubrr.Currency.CurrencyMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.idamobile.protocol.ubrr.Currency.CurrencyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.idamobile.protocol.ubrr.Currency.internal_static_messaging_CurrencyMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.idamobile.protocol.ubrr.Currency.internal_static_messaging_CurrencyMessage_fieldAccessorTable;
      }
      
      // Construct using com.idamobile.protocol.ubrr.Currency.CurrencyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        operation_ = com.idamobile.protocol.ubrr.Currency.CurrencyOperation.BUY;
        bitField0_ = (bitField0_ & ~0x00000001);
        currency_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        price_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        amount_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        delta_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.idamobile.protocol.ubrr.Currency.CurrencyMessage.getDescriptor();
      }
      
      public com.idamobile.protocol.ubrr.Currency.CurrencyMessage getDefaultInstanceForType() {
        return com.idamobile.protocol.ubrr.Currency.CurrencyMessage.getDefaultInstance();
      }
      
      public com.idamobile.protocol.ubrr.Currency.CurrencyMessage build() {
        com.idamobile.protocol.ubrr.Currency.CurrencyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.idamobile.protocol.ubrr.Currency.CurrencyMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.idamobile.protocol.ubrr.Currency.CurrencyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.idamobile.protocol.ubrr.Currency.CurrencyMessage buildPartial() {
        com.idamobile.protocol.ubrr.Currency.CurrencyMessage result = new com.idamobile.protocol.ubrr.Currency.CurrencyMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.operation_ = operation_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.currency_ = currency_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.price_ = price_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.amount_ = amount_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.delta_ = delta_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.idamobile.protocol.ubrr.Currency.CurrencyMessage) {
          return mergeFrom((com.idamobile.protocol.ubrr.Currency.CurrencyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.idamobile.protocol.ubrr.Currency.CurrencyMessage other) {
        if (other == com.idamobile.protocol.ubrr.Currency.CurrencyMessage.getDefaultInstance()) return this;
        if (other.hasOperation()) {
          setOperation(other.getOperation());
        }
        if (other.hasCurrency()) {
          setCurrency(other.getCurrency());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        if (other.hasAmount()) {
          setAmount(other.getAmount());
        }
        if (other.hasDelta()) {
          setDelta(other.getDelta());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasOperation()) {
          
          return false;
        }
        if (!hasCurrency()) {
          
          return false;
        }
        if (!hasPrice()) {
          
          return false;
        }
        if (!hasAmount()) {
          
          return false;
        }
        if (!hasDelta()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.idamobile.protocol.ubrr.Currency.CurrencyOperation value = com.idamobile.protocol.ubrr.Currency.CurrencyOperation.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                operation_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              currency_ = input.readInt32();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              price_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              amount_ = input.readDouble();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              delta_ = input.readDouble();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .messaging.CurrencyOperation operation = 1;
      private com.idamobile.protocol.ubrr.Currency.CurrencyOperation operation_ = com.idamobile.protocol.ubrr.Currency.CurrencyOperation.BUY;
      public boolean hasOperation() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.idamobile.protocol.ubrr.Currency.CurrencyOperation getOperation() {
        return operation_;
      }
      public Builder setOperation(com.idamobile.protocol.ubrr.Currency.CurrencyOperation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        operation_ = value;
        onChanged();
        return this;
      }
      public Builder clearOperation() {
        bitField0_ = (bitField0_ & ~0x00000001);
        operation_ = com.idamobile.protocol.ubrr.Currency.CurrencyOperation.BUY;
        onChanged();
        return this;
      }
      
      // required int32 currency = 2;
      private int currency_ ;
      public boolean hasCurrency() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getCurrency() {
        return currency_;
      }
      public Builder setCurrency(int value) {
        bitField0_ |= 0x00000002;
        currency_ = value;
        onChanged();
        return this;
      }
      public Builder clearCurrency() {
        bitField0_ = (bitField0_ & ~0x00000002);
        currency_ = 0;
        onChanged();
        return this;
      }
      
      // required double price = 3;
      private double price_ ;
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public double getPrice() {
        return price_;
      }
      public Builder setPrice(double value) {
        bitField0_ |= 0x00000004;
        price_ = value;
        onChanged();
        return this;
      }
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000004);
        price_ = 0D;
        onChanged();
        return this;
      }
      
      // required double amount = 4;
      private double amount_ ;
      public boolean hasAmount() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public double getAmount() {
        return amount_;
      }
      public Builder setAmount(double value) {
        bitField0_ |= 0x00000008;
        amount_ = value;
        onChanged();
        return this;
      }
      public Builder clearAmount() {
        bitField0_ = (bitField0_ & ~0x00000008);
        amount_ = 0D;
        onChanged();
        return this;
      }
      
      // required double delta = 5;
      private double delta_ ;
      public boolean hasDelta() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public double getDelta() {
        return delta_;
      }
      public Builder setDelta(double value) {
        bitField0_ |= 0x00000010;
        delta_ = value;
        onChanged();
        return this;
      }
      public Builder clearDelta() {
        bitField0_ = (bitField0_ & ~0x00000010);
        delta_ = 0D;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:messaging.CurrencyMessage)
    }
    
    static {
      defaultInstance = new CurrencyMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:messaging.CurrencyMessage)
  }
  
  public interface CurrencyRateRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  public static final class CurrencyRateRequest extends
      com.google.protobuf.GeneratedMessage
      implements CurrencyRateRequestOrBuilder {
    // Use CurrencyRateRequest.newBuilder() to construct.
    private CurrencyRateRequest(Builder builder) {
      super(builder);
    }
    private CurrencyRateRequest(boolean noInit) {}
    
    private static final CurrencyRateRequest defaultInstance;
    public static CurrencyRateRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public CurrencyRateRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.idamobile.protocol.ubrr.Currency.internal_static_messaging_CurrencyRateRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.idamobile.protocol.ubrr.Currency.internal_static_messaging_CurrencyRateRequest_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.idamobile.protocol.ubrr.Currency.CurrencyRateRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.idamobile.protocol.ubrr.Currency.internal_static_messaging_CurrencyRateRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.idamobile.protocol.ubrr.Currency.internal_static_messaging_CurrencyRateRequest_fieldAccessorTable;
      }
      
      // Construct using com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest.getDescriptor();
      }
      
      public com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest getDefaultInstanceForType() {
        return com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest.getDefaultInstance();
      }
      
      public com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest build() {
        com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest buildPartial() {
        com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest result = new com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest(this);
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest) {
          return mergeFrom((com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest other) {
        if (other == com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:messaging.CurrencyRateRequest)
    }
    
    static {
      defaultInstance = new CurrencyRateRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:messaging.CurrencyRateRequest)
  }
  
  public interface CurrencyRateResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 lastUpdateTime = 1;
    boolean hasLastUpdateTime();
    long getLastUpdateTime();
    
    // repeated .messaging.CurrencyMessage currency = 2;
    java.util.List<com.idamobile.protocol.ubrr.Currency.CurrencyMessage> 
        getCurrencyList();
    com.idamobile.protocol.ubrr.Currency.CurrencyMessage getCurrency(int index);
    int getCurrencyCount();
    java.util.List<? extends com.idamobile.protocol.ubrr.Currency.CurrencyMessageOrBuilder> 
        getCurrencyOrBuilderList();
    com.idamobile.protocol.ubrr.Currency.CurrencyMessageOrBuilder getCurrencyOrBuilder(
        int index);
  }
  public static final class CurrencyRateResponse extends
      com.google.protobuf.GeneratedMessage
      implements CurrencyRateResponseOrBuilder {
    // Use CurrencyRateResponse.newBuilder() to construct.
    private CurrencyRateResponse(Builder builder) {
      super(builder);
    }
    private CurrencyRateResponse(boolean noInit) {}
    
    private static final CurrencyRateResponse defaultInstance;
    public static CurrencyRateResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public CurrencyRateResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.idamobile.protocol.ubrr.Currency.internal_static_messaging_CurrencyRateResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.idamobile.protocol.ubrr.Currency.internal_static_messaging_CurrencyRateResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int64 lastUpdateTime = 1;
    public static final int LASTUPDATETIME_FIELD_NUMBER = 1;
    private long lastUpdateTime_;
    public boolean hasLastUpdateTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getLastUpdateTime() {
      return lastUpdateTime_;
    }
    
    // repeated .messaging.CurrencyMessage currency = 2;
    public static final int CURRENCY_FIELD_NUMBER = 2;
    private java.util.List<com.idamobile.protocol.ubrr.Currency.CurrencyMessage> currency_;
    public java.util.List<com.idamobile.protocol.ubrr.Currency.CurrencyMessage> getCurrencyList() {
      return currency_;
    }
    public java.util.List<? extends com.idamobile.protocol.ubrr.Currency.CurrencyMessageOrBuilder> 
        getCurrencyOrBuilderList() {
      return currency_;
    }
    public int getCurrencyCount() {
      return currency_.size();
    }
    public com.idamobile.protocol.ubrr.Currency.CurrencyMessage getCurrency(int index) {
      return currency_.get(index);
    }
    public com.idamobile.protocol.ubrr.Currency.CurrencyMessageOrBuilder getCurrencyOrBuilder(
        int index) {
      return currency_.get(index);
    }
    
    private void initFields() {
      lastUpdateTime_ = 0L;
      currency_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasLastUpdateTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getCurrencyCount(); i++) {
        if (!getCurrency(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, lastUpdateTime_);
      }
      for (int i = 0; i < currency_.size(); i++) {
        output.writeMessage(2, currency_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, lastUpdateTime_);
      }
      for (int i = 0; i < currency_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, currency_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.idamobile.protocol.ubrr.Currency.CurrencyRateResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.idamobile.protocol.ubrr.Currency.internal_static_messaging_CurrencyRateResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.idamobile.protocol.ubrr.Currency.internal_static_messaging_CurrencyRateResponse_fieldAccessorTable;
      }
      
      // Construct using com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCurrencyFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        lastUpdateTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (currencyBuilder_ == null) {
          currency_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          currencyBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse.getDescriptor();
      }
      
      public com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse getDefaultInstanceForType() {
        return com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse.getDefaultInstance();
      }
      
      public com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse build() {
        com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse buildPartial() {
        com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse result = new com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.lastUpdateTime_ = lastUpdateTime_;
        if (currencyBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            currency_ = java.util.Collections.unmodifiableList(currency_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.currency_ = currency_;
        } else {
          result.currency_ = currencyBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse) {
          return mergeFrom((com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse other) {
        if (other == com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse.getDefaultInstance()) return this;
        if (other.hasLastUpdateTime()) {
          setLastUpdateTime(other.getLastUpdateTime());
        }
        if (currencyBuilder_ == null) {
          if (!other.currency_.isEmpty()) {
            if (currency_.isEmpty()) {
              currency_ = other.currency_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureCurrencyIsMutable();
              currency_.addAll(other.currency_);
            }
            onChanged();
          }
        } else {
          if (!other.currency_.isEmpty()) {
            if (currencyBuilder_.isEmpty()) {
              currencyBuilder_.dispose();
              currencyBuilder_ = null;
              currency_ = other.currency_;
              bitField0_ = (bitField0_ & ~0x00000002);
              currencyBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCurrencyFieldBuilder() : null;
            } else {
              currencyBuilder_.addAllMessages(other.currency_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasLastUpdateTime()) {
          
          return false;
        }
        for (int i = 0; i < getCurrencyCount(); i++) {
          if (!getCurrency(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              lastUpdateTime_ = input.readInt64();
              break;
            }
            case 18: {
              com.idamobile.protocol.ubrr.Currency.CurrencyMessage.Builder subBuilder = com.idamobile.protocol.ubrr.Currency.CurrencyMessage.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addCurrency(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 lastUpdateTime = 1;
      private long lastUpdateTime_ ;
      public boolean hasLastUpdateTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getLastUpdateTime() {
        return lastUpdateTime_;
      }
      public Builder setLastUpdateTime(long value) {
        bitField0_ |= 0x00000001;
        lastUpdateTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearLastUpdateTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        lastUpdateTime_ = 0L;
        onChanged();
        return this;
      }
      
      // repeated .messaging.CurrencyMessage currency = 2;
      private java.util.List<com.idamobile.protocol.ubrr.Currency.CurrencyMessage> currency_ =
        java.util.Collections.emptyList();
      private void ensureCurrencyIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          currency_ = new java.util.ArrayList<com.idamobile.protocol.ubrr.Currency.CurrencyMessage>(currency_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.idamobile.protocol.ubrr.Currency.CurrencyMessage, com.idamobile.protocol.ubrr.Currency.CurrencyMessage.Builder, com.idamobile.protocol.ubrr.Currency.CurrencyMessageOrBuilder> currencyBuilder_;
      
      public java.util.List<com.idamobile.protocol.ubrr.Currency.CurrencyMessage> getCurrencyList() {
        if (currencyBuilder_ == null) {
          return java.util.Collections.unmodifiableList(currency_);
        } else {
          return currencyBuilder_.getMessageList();
        }
      }
      public int getCurrencyCount() {
        if (currencyBuilder_ == null) {
          return currency_.size();
        } else {
          return currencyBuilder_.getCount();
        }
      }
      public com.idamobile.protocol.ubrr.Currency.CurrencyMessage getCurrency(int index) {
        if (currencyBuilder_ == null) {
          return currency_.get(index);
        } else {
          return currencyBuilder_.getMessage(index);
        }
      }
      public Builder setCurrency(
          int index, com.idamobile.protocol.ubrr.Currency.CurrencyMessage value) {
        if (currencyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCurrencyIsMutable();
          currency_.set(index, value);
          onChanged();
        } else {
          currencyBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setCurrency(
          int index, com.idamobile.protocol.ubrr.Currency.CurrencyMessage.Builder builderForValue) {
        if (currencyBuilder_ == null) {
          ensureCurrencyIsMutable();
          currency_.set(index, builderForValue.build());
          onChanged();
        } else {
          currencyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addCurrency(com.idamobile.protocol.ubrr.Currency.CurrencyMessage value) {
        if (currencyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCurrencyIsMutable();
          currency_.add(value);
          onChanged();
        } else {
          currencyBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addCurrency(
          int index, com.idamobile.protocol.ubrr.Currency.CurrencyMessage value) {
        if (currencyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCurrencyIsMutable();
          currency_.add(index, value);
          onChanged();
        } else {
          currencyBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addCurrency(
          com.idamobile.protocol.ubrr.Currency.CurrencyMessage.Builder builderForValue) {
        if (currencyBuilder_ == null) {
          ensureCurrencyIsMutable();
          currency_.add(builderForValue.build());
          onChanged();
        } else {
          currencyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addCurrency(
          int index, com.idamobile.protocol.ubrr.Currency.CurrencyMessage.Builder builderForValue) {
        if (currencyBuilder_ == null) {
          ensureCurrencyIsMutable();
          currency_.add(index, builderForValue.build());
          onChanged();
        } else {
          currencyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllCurrency(
          java.lang.Iterable<? extends com.idamobile.protocol.ubrr.Currency.CurrencyMessage> values) {
        if (currencyBuilder_ == null) {
          ensureCurrencyIsMutable();
          super.addAll(values, currency_);
          onChanged();
        } else {
          currencyBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearCurrency() {
        if (currencyBuilder_ == null) {
          currency_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          currencyBuilder_.clear();
        }
        return this;
      }
      public Builder removeCurrency(int index) {
        if (currencyBuilder_ == null) {
          ensureCurrencyIsMutable();
          currency_.remove(index);
          onChanged();
        } else {
          currencyBuilder_.remove(index);
        }
        return this;
      }
      public com.idamobile.protocol.ubrr.Currency.CurrencyMessage.Builder getCurrencyBuilder(
          int index) {
        return getCurrencyFieldBuilder().getBuilder(index);
      }
      public com.idamobile.protocol.ubrr.Currency.CurrencyMessageOrBuilder getCurrencyOrBuilder(
          int index) {
        if (currencyBuilder_ == null) {
          return currency_.get(index);  } else {
          return currencyBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.idamobile.protocol.ubrr.Currency.CurrencyMessageOrBuilder> 
           getCurrencyOrBuilderList() {
        if (currencyBuilder_ != null) {
          return currencyBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(currency_);
        }
      }
      public com.idamobile.protocol.ubrr.Currency.CurrencyMessage.Builder addCurrencyBuilder() {
        return getCurrencyFieldBuilder().addBuilder(
            com.idamobile.protocol.ubrr.Currency.CurrencyMessage.getDefaultInstance());
      }
      public com.idamobile.protocol.ubrr.Currency.CurrencyMessage.Builder addCurrencyBuilder(
          int index) {
        return getCurrencyFieldBuilder().addBuilder(
            index, com.idamobile.protocol.ubrr.Currency.CurrencyMessage.getDefaultInstance());
      }
      public java.util.List<com.idamobile.protocol.ubrr.Currency.CurrencyMessage.Builder> 
           getCurrencyBuilderList() {
        return getCurrencyFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.idamobile.protocol.ubrr.Currency.CurrencyMessage, com.idamobile.protocol.ubrr.Currency.CurrencyMessage.Builder, com.idamobile.protocol.ubrr.Currency.CurrencyMessageOrBuilder> 
          getCurrencyFieldBuilder() {
        if (currencyBuilder_ == null) {
          currencyBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.idamobile.protocol.ubrr.Currency.CurrencyMessage, com.idamobile.protocol.ubrr.Currency.CurrencyMessage.Builder, com.idamobile.protocol.ubrr.Currency.CurrencyMessageOrBuilder>(
                  currency_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          currency_ = null;
        }
        return currencyBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:messaging.CurrencyRateResponse)
    }
    
    static {
      defaultInstance = new CurrencyRateResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:messaging.CurrencyRateResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messaging_CurrencyMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messaging_CurrencyMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messaging_CurrencyRateRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messaging_CurrencyRateRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messaging_CurrencyRateResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messaging_CurrencyRateResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016currency.proto\022\tmessaging\"\202\001\n\017Currency" +
      "Message\022/\n\toperation\030\001 \002(\0162\034.messaging.C" +
      "urrencyOperation\022\020\n\010currency\030\002 \002(\005\022\r\n\005pr" +
      "ice\030\003 \002(\001\022\016\n\006amount\030\004 \002(\001\022\r\n\005delta\030\005 \002(\001" +
      "\"\025\n\023CurrencyRateRequest\"\\\n\024CurrencyRateR" +
      "esponse\022\026\n\016lastUpdateTime\030\001 \002(\003\022,\n\010curre" +
      "ncy\030\002 \003(\0132\032.messaging.CurrencyMessage*3\n" +
      "\021CurrencyOperation\022\007\n\003BUY\020\000\022\010\n\004SELL\020\001\022\013\n" +
      "\007CENTRAL\020\002B\035\n\033com.idamobile.protocol.ubr" +
      "r"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_messaging_CurrencyMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_messaging_CurrencyMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messaging_CurrencyMessage_descriptor,
              new java.lang.String[] { "Operation", "Currency", "Price", "Amount", "Delta", },
              com.idamobile.protocol.ubrr.Currency.CurrencyMessage.class,
              com.idamobile.protocol.ubrr.Currency.CurrencyMessage.Builder.class);
          internal_static_messaging_CurrencyRateRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_messaging_CurrencyRateRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messaging_CurrencyRateRequest_descriptor,
              new java.lang.String[] { },
              com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest.class,
              com.idamobile.protocol.ubrr.Currency.CurrencyRateRequest.Builder.class);
          internal_static_messaging_CurrencyRateResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_messaging_CurrencyRateResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messaging_CurrencyRateResponse_descriptor,
              new java.lang.String[] { "LastUpdateTime", "Currency", },
              com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse.class,
              com.idamobile.protocol.ubrr.Currency.CurrencyRateResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
