// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: news.proto

package com.idamobile.protocol.ubrr;

public final class News {
  private News() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NewsMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 id = 1;
    boolean hasId();
    int getId();
    
    // required string title = 2;
    boolean hasTitle();
    String getTitle();
    
    // optional string preview = 3;
    boolean hasPreview();
    String getPreview();
    
    // optional string url = 4;
    boolean hasUrl();
    String getUrl();
    
    // optional string htmlBody = 5;
    boolean hasHtmlBody();
    String getHtmlBody();
    
    // optional int64 creationDate = 6;
    boolean hasCreationDate();
    long getCreationDate();
  }
  public static final class NewsMessage extends
      com.google.protobuf.GeneratedMessage
      implements NewsMessageOrBuilder {
    // Use NewsMessage.newBuilder() to construct.
    private NewsMessage(Builder builder) {
      super(builder);
    }
    private NewsMessage(boolean noInit) {}
    
    private static final NewsMessage defaultInstance;
    public static NewsMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public NewsMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.idamobile.protocol.ubrr.News.internal_static_messaging_NewsMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.idamobile.protocol.ubrr.News.internal_static_messaging_NewsMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    // required string title = 2;
    public static final int TITLE_FIELD_NUMBER = 2;
    private java.lang.Object title_;
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          title_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string preview = 3;
    public static final int PREVIEW_FIELD_NUMBER = 3;
    private java.lang.Object preview_;
    public boolean hasPreview() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getPreview() {
      java.lang.Object ref = preview_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          preview_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPreviewBytes() {
      java.lang.Object ref = preview_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        preview_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string url = 4;
    public static final int URL_FIELD_NUMBER = 4;
    private java.lang.Object url_;
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          url_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string htmlBody = 5;
    public static final int HTMLBODY_FIELD_NUMBER = 5;
    private java.lang.Object htmlBody_;
    public boolean hasHtmlBody() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getHtmlBody() {
      java.lang.Object ref = htmlBody_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          htmlBody_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getHtmlBodyBytes() {
      java.lang.Object ref = htmlBody_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        htmlBody_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 creationDate = 6;
    public static final int CREATIONDATE_FIELD_NUMBER = 6;
    private long creationDate_;
    public boolean hasCreationDate() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public long getCreationDate() {
      return creationDate_;
    }
    
    private void initFields() {
      id_ = 0;
      title_ = "";
      preview_ = "";
      url_ = "";
      htmlBody_ = "";
      creationDate_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPreviewBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getUrlBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getHtmlBodyBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, creationDate_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPreviewBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getUrlBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getHtmlBodyBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, creationDate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.idamobile.protocol.ubrr.News.NewsMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.News.NewsMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.News.NewsMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.News.NewsMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.News.NewsMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.News.NewsMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.News.NewsMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.idamobile.protocol.ubrr.News.NewsMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.idamobile.protocol.ubrr.News.NewsMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.News.NewsMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.idamobile.protocol.ubrr.News.NewsMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.idamobile.protocol.ubrr.News.NewsMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.idamobile.protocol.ubrr.News.internal_static_messaging_NewsMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.idamobile.protocol.ubrr.News.internal_static_messaging_NewsMessage_fieldAccessorTable;
      }
      
      // Construct using com.idamobile.protocol.ubrr.News.NewsMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        preview_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        htmlBody_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        creationDate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.idamobile.protocol.ubrr.News.NewsMessage.getDescriptor();
      }
      
      public com.idamobile.protocol.ubrr.News.NewsMessage getDefaultInstanceForType() {
        return com.idamobile.protocol.ubrr.News.NewsMessage.getDefaultInstance();
      }
      
      public com.idamobile.protocol.ubrr.News.NewsMessage build() {
        com.idamobile.protocol.ubrr.News.NewsMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.idamobile.protocol.ubrr.News.NewsMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.idamobile.protocol.ubrr.News.NewsMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.idamobile.protocol.ubrr.News.NewsMessage buildPartial() {
        com.idamobile.protocol.ubrr.News.NewsMessage result = new com.idamobile.protocol.ubrr.News.NewsMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.preview_ = preview_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.url_ = url_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.htmlBody_ = htmlBody_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.creationDate_ = creationDate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.idamobile.protocol.ubrr.News.NewsMessage) {
          return mergeFrom((com.idamobile.protocol.ubrr.News.NewsMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.idamobile.protocol.ubrr.News.NewsMessage other) {
        if (other == com.idamobile.protocol.ubrr.News.NewsMessage.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasPreview()) {
          setPreview(other.getPreview());
        }
        if (other.hasUrl()) {
          setUrl(other.getUrl());
        }
        if (other.hasHtmlBody()) {
          setHtmlBody(other.getHtmlBody());
        }
        if (other.hasCreationDate()) {
          setCreationDate(other.getCreationDate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasTitle()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              title_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              preview_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              url_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              htmlBody_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              creationDate_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // required string title = 2;
      private java.lang.Object title_ = "";
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTitle(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      void setTitle(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
      }
      
      // optional string preview = 3;
      private java.lang.Object preview_ = "";
      public boolean hasPreview() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getPreview() {
        java.lang.Object ref = preview_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          preview_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPreview(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        preview_ = value;
        onChanged();
        return this;
      }
      public Builder clearPreview() {
        bitField0_ = (bitField0_ & ~0x00000004);
        preview_ = getDefaultInstance().getPreview();
        onChanged();
        return this;
      }
      void setPreview(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        preview_ = value;
        onChanged();
      }
      
      // optional string url = 4;
      private java.lang.Object url_ = "";
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUrl(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        url_ = value;
        onChanged();
        return this;
      }
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000008);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      void setUrl(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        url_ = value;
        onChanged();
      }
      
      // optional string htmlBody = 5;
      private java.lang.Object htmlBody_ = "";
      public boolean hasHtmlBody() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getHtmlBody() {
        java.lang.Object ref = htmlBody_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          htmlBody_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setHtmlBody(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        htmlBody_ = value;
        onChanged();
        return this;
      }
      public Builder clearHtmlBody() {
        bitField0_ = (bitField0_ & ~0x00000010);
        htmlBody_ = getDefaultInstance().getHtmlBody();
        onChanged();
        return this;
      }
      void setHtmlBody(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        htmlBody_ = value;
        onChanged();
      }
      
      // optional int64 creationDate = 6;
      private long creationDate_ ;
      public boolean hasCreationDate() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public long getCreationDate() {
        return creationDate_;
      }
      public Builder setCreationDate(long value) {
        bitField0_ |= 0x00000020;
        creationDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearCreationDate() {
        bitField0_ = (bitField0_ & ~0x00000020);
        creationDate_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:messaging.NewsMessage)
    }
    
    static {
      defaultInstance = new NewsMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:messaging.NewsMessage)
  }
  
  public interface NewsRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated int32 newsIds = 1;
    java.util.List<java.lang.Integer> getNewsIdsList();
    int getNewsIdsCount();
    int getNewsIds(int index);
  }
  public static final class NewsRequest extends
      com.google.protobuf.GeneratedMessage
      implements NewsRequestOrBuilder {
    // Use NewsRequest.newBuilder() to construct.
    private NewsRequest(Builder builder) {
      super(builder);
    }
    private NewsRequest(boolean noInit) {}
    
    private static final NewsRequest defaultInstance;
    public static NewsRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public NewsRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.idamobile.protocol.ubrr.News.internal_static_messaging_NewsRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.idamobile.protocol.ubrr.News.internal_static_messaging_NewsRequest_fieldAccessorTable;
    }
    
    // repeated int32 newsIds = 1;
    public static final int NEWSIDS_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> newsIds_;
    public java.util.List<java.lang.Integer>
        getNewsIdsList() {
      return newsIds_;
    }
    public int getNewsIdsCount() {
      return newsIds_.size();
    }
    public int getNewsIds(int index) {
      return newsIds_.get(index);
    }
    
    private void initFields() {
      newsIds_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < newsIds_.size(); i++) {
        output.writeInt32(1, newsIds_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < newsIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(newsIds_.get(i));
        }
        size += dataSize;
        size += 1 * getNewsIdsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.idamobile.protocol.ubrr.News.NewsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.News.NewsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.News.NewsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.News.NewsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.News.NewsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.News.NewsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.News.NewsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.idamobile.protocol.ubrr.News.NewsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.idamobile.protocol.ubrr.News.NewsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.News.NewsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.idamobile.protocol.ubrr.News.NewsRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.idamobile.protocol.ubrr.News.NewsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.idamobile.protocol.ubrr.News.internal_static_messaging_NewsRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.idamobile.protocol.ubrr.News.internal_static_messaging_NewsRequest_fieldAccessorTable;
      }
      
      // Construct using com.idamobile.protocol.ubrr.News.NewsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        newsIds_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.idamobile.protocol.ubrr.News.NewsRequest.getDescriptor();
      }
      
      public com.idamobile.protocol.ubrr.News.NewsRequest getDefaultInstanceForType() {
        return com.idamobile.protocol.ubrr.News.NewsRequest.getDefaultInstance();
      }
      
      public com.idamobile.protocol.ubrr.News.NewsRequest build() {
        com.idamobile.protocol.ubrr.News.NewsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.idamobile.protocol.ubrr.News.NewsRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.idamobile.protocol.ubrr.News.NewsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.idamobile.protocol.ubrr.News.NewsRequest buildPartial() {
        com.idamobile.protocol.ubrr.News.NewsRequest result = new com.idamobile.protocol.ubrr.News.NewsRequest(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          newsIds_ = java.util.Collections.unmodifiableList(newsIds_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.newsIds_ = newsIds_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.idamobile.protocol.ubrr.News.NewsRequest) {
          return mergeFrom((com.idamobile.protocol.ubrr.News.NewsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.idamobile.protocol.ubrr.News.NewsRequest other) {
        if (other == com.idamobile.protocol.ubrr.News.NewsRequest.getDefaultInstance()) return this;
        if (!other.newsIds_.isEmpty()) {
          if (newsIds_.isEmpty()) {
            newsIds_ = other.newsIds_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNewsIdsIsMutable();
            newsIds_.addAll(other.newsIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              ensureNewsIdsIsMutable();
              newsIds_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addNewsIds(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated int32 newsIds = 1;
      private java.util.List<java.lang.Integer> newsIds_ = java.util.Collections.emptyList();;
      private void ensureNewsIdsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          newsIds_ = new java.util.ArrayList<java.lang.Integer>(newsIds_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<java.lang.Integer>
          getNewsIdsList() {
        return java.util.Collections.unmodifiableList(newsIds_);
      }
      public int getNewsIdsCount() {
        return newsIds_.size();
      }
      public int getNewsIds(int index) {
        return newsIds_.get(index);
      }
      public Builder setNewsIds(
          int index, int value) {
        ensureNewsIdsIsMutable();
        newsIds_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addNewsIds(int value) {
        ensureNewsIdsIsMutable();
        newsIds_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllNewsIds(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureNewsIdsIsMutable();
        super.addAll(values, newsIds_);
        onChanged();
        return this;
      }
      public Builder clearNewsIds() {
        newsIds_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:messaging.NewsRequest)
    }
    
    static {
      defaultInstance = new NewsRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:messaging.NewsRequest)
  }
  
  public interface NewsResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .messaging.NewsMessage news = 1;
    java.util.List<com.idamobile.protocol.ubrr.News.NewsMessage> 
        getNewsList();
    com.idamobile.protocol.ubrr.News.NewsMessage getNews(int index);
    int getNewsCount();
    java.util.List<? extends com.idamobile.protocol.ubrr.News.NewsMessageOrBuilder> 
        getNewsOrBuilderList();
    com.idamobile.protocol.ubrr.News.NewsMessageOrBuilder getNewsOrBuilder(
        int index);
    
    // repeated int32 deletedIds = 2;
    java.util.List<java.lang.Integer> getDeletedIdsList();
    int getDeletedIdsCount();
    int getDeletedIds(int index);
  }
  public static final class NewsResponse extends
      com.google.protobuf.GeneratedMessage
      implements NewsResponseOrBuilder {
    // Use NewsResponse.newBuilder() to construct.
    private NewsResponse(Builder builder) {
      super(builder);
    }
    private NewsResponse(boolean noInit) {}
    
    private static final NewsResponse defaultInstance;
    public static NewsResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public NewsResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.idamobile.protocol.ubrr.News.internal_static_messaging_NewsResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.idamobile.protocol.ubrr.News.internal_static_messaging_NewsResponse_fieldAccessorTable;
    }
    
    // repeated .messaging.NewsMessage news = 1;
    public static final int NEWS_FIELD_NUMBER = 1;
    private java.util.List<com.idamobile.protocol.ubrr.News.NewsMessage> news_;
    public java.util.List<com.idamobile.protocol.ubrr.News.NewsMessage> getNewsList() {
      return news_;
    }
    public java.util.List<? extends com.idamobile.protocol.ubrr.News.NewsMessageOrBuilder> 
        getNewsOrBuilderList() {
      return news_;
    }
    public int getNewsCount() {
      return news_.size();
    }
    public com.idamobile.protocol.ubrr.News.NewsMessage getNews(int index) {
      return news_.get(index);
    }
    public com.idamobile.protocol.ubrr.News.NewsMessageOrBuilder getNewsOrBuilder(
        int index) {
      return news_.get(index);
    }
    
    // repeated int32 deletedIds = 2;
    public static final int DELETEDIDS_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> deletedIds_;
    public java.util.List<java.lang.Integer>
        getDeletedIdsList() {
      return deletedIds_;
    }
    public int getDeletedIdsCount() {
      return deletedIds_.size();
    }
    public int getDeletedIds(int index) {
      return deletedIds_.get(index);
    }
    
    private void initFields() {
      news_ = java.util.Collections.emptyList();
      deletedIds_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getNewsCount(); i++) {
        if (!getNews(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < news_.size(); i++) {
        output.writeMessage(1, news_.get(i));
      }
      for (int i = 0; i < deletedIds_.size(); i++) {
        output.writeInt32(2, deletedIds_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < news_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, news_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < deletedIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(deletedIds_.get(i));
        }
        size += dataSize;
        size += 1 * getDeletedIdsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.idamobile.protocol.ubrr.News.NewsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.News.NewsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.News.NewsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.News.NewsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.News.NewsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.News.NewsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.idamobile.protocol.ubrr.News.NewsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.idamobile.protocol.ubrr.News.NewsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.idamobile.protocol.ubrr.News.NewsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.idamobile.protocol.ubrr.News.NewsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.idamobile.protocol.ubrr.News.NewsResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.idamobile.protocol.ubrr.News.NewsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.idamobile.protocol.ubrr.News.internal_static_messaging_NewsResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.idamobile.protocol.ubrr.News.internal_static_messaging_NewsResponse_fieldAccessorTable;
      }
      
      // Construct using com.idamobile.protocol.ubrr.News.NewsResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNewsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (newsBuilder_ == null) {
          news_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          newsBuilder_.clear();
        }
        deletedIds_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.idamobile.protocol.ubrr.News.NewsResponse.getDescriptor();
      }
      
      public com.idamobile.protocol.ubrr.News.NewsResponse getDefaultInstanceForType() {
        return com.idamobile.protocol.ubrr.News.NewsResponse.getDefaultInstance();
      }
      
      public com.idamobile.protocol.ubrr.News.NewsResponse build() {
        com.idamobile.protocol.ubrr.News.NewsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.idamobile.protocol.ubrr.News.NewsResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.idamobile.protocol.ubrr.News.NewsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.idamobile.protocol.ubrr.News.NewsResponse buildPartial() {
        com.idamobile.protocol.ubrr.News.NewsResponse result = new com.idamobile.protocol.ubrr.News.NewsResponse(this);
        int from_bitField0_ = bitField0_;
        if (newsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            news_ = java.util.Collections.unmodifiableList(news_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.news_ = news_;
        } else {
          result.news_ = newsBuilder_.build();
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          deletedIds_ = java.util.Collections.unmodifiableList(deletedIds_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.deletedIds_ = deletedIds_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.idamobile.protocol.ubrr.News.NewsResponse) {
          return mergeFrom((com.idamobile.protocol.ubrr.News.NewsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.idamobile.protocol.ubrr.News.NewsResponse other) {
        if (other == com.idamobile.protocol.ubrr.News.NewsResponse.getDefaultInstance()) return this;
        if (newsBuilder_ == null) {
          if (!other.news_.isEmpty()) {
            if (news_.isEmpty()) {
              news_ = other.news_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNewsIsMutable();
              news_.addAll(other.news_);
            }
            onChanged();
          }
        } else {
          if (!other.news_.isEmpty()) {
            if (newsBuilder_.isEmpty()) {
              newsBuilder_.dispose();
              newsBuilder_ = null;
              news_ = other.news_;
              bitField0_ = (bitField0_ & ~0x00000001);
              newsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNewsFieldBuilder() : null;
            } else {
              newsBuilder_.addAllMessages(other.news_);
            }
          }
        }
        if (!other.deletedIds_.isEmpty()) {
          if (deletedIds_.isEmpty()) {
            deletedIds_ = other.deletedIds_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDeletedIdsIsMutable();
            deletedIds_.addAll(other.deletedIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getNewsCount(); i++) {
          if (!getNews(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.idamobile.protocol.ubrr.News.NewsMessage.Builder subBuilder = com.idamobile.protocol.ubrr.News.NewsMessage.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addNews(subBuilder.buildPartial());
              break;
            }
            case 16: {
              ensureDeletedIdsIsMutable();
              deletedIds_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addDeletedIds(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .messaging.NewsMessage news = 1;
      private java.util.List<com.idamobile.protocol.ubrr.News.NewsMessage> news_ =
        java.util.Collections.emptyList();
      private void ensureNewsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          news_ = new java.util.ArrayList<com.idamobile.protocol.ubrr.News.NewsMessage>(news_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.idamobile.protocol.ubrr.News.NewsMessage, com.idamobile.protocol.ubrr.News.NewsMessage.Builder, com.idamobile.protocol.ubrr.News.NewsMessageOrBuilder> newsBuilder_;
      
      public java.util.List<com.idamobile.protocol.ubrr.News.NewsMessage> getNewsList() {
        if (newsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(news_);
        } else {
          return newsBuilder_.getMessageList();
        }
      }
      public int getNewsCount() {
        if (newsBuilder_ == null) {
          return news_.size();
        } else {
          return newsBuilder_.getCount();
        }
      }
      public com.idamobile.protocol.ubrr.News.NewsMessage getNews(int index) {
        if (newsBuilder_ == null) {
          return news_.get(index);
        } else {
          return newsBuilder_.getMessage(index);
        }
      }
      public Builder setNews(
          int index, com.idamobile.protocol.ubrr.News.NewsMessage value) {
        if (newsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewsIsMutable();
          news_.set(index, value);
          onChanged();
        } else {
          newsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setNews(
          int index, com.idamobile.protocol.ubrr.News.NewsMessage.Builder builderForValue) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          news_.set(index, builderForValue.build());
          onChanged();
        } else {
          newsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addNews(com.idamobile.protocol.ubrr.News.NewsMessage value) {
        if (newsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewsIsMutable();
          news_.add(value);
          onChanged();
        } else {
          newsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addNews(
          int index, com.idamobile.protocol.ubrr.News.NewsMessage value) {
        if (newsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewsIsMutable();
          news_.add(index, value);
          onChanged();
        } else {
          newsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addNews(
          com.idamobile.protocol.ubrr.News.NewsMessage.Builder builderForValue) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          news_.add(builderForValue.build());
          onChanged();
        } else {
          newsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addNews(
          int index, com.idamobile.protocol.ubrr.News.NewsMessage.Builder builderForValue) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          news_.add(index, builderForValue.build());
          onChanged();
        } else {
          newsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllNews(
          java.lang.Iterable<? extends com.idamobile.protocol.ubrr.News.NewsMessage> values) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          super.addAll(values, news_);
          onChanged();
        } else {
          newsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearNews() {
        if (newsBuilder_ == null) {
          news_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          newsBuilder_.clear();
        }
        return this;
      }
      public Builder removeNews(int index) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          news_.remove(index);
          onChanged();
        } else {
          newsBuilder_.remove(index);
        }
        return this;
      }
      public com.idamobile.protocol.ubrr.News.NewsMessage.Builder getNewsBuilder(
          int index) {
        return getNewsFieldBuilder().getBuilder(index);
      }
      public com.idamobile.protocol.ubrr.News.NewsMessageOrBuilder getNewsOrBuilder(
          int index) {
        if (newsBuilder_ == null) {
          return news_.get(index);  } else {
          return newsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.idamobile.protocol.ubrr.News.NewsMessageOrBuilder> 
           getNewsOrBuilderList() {
        if (newsBuilder_ != null) {
          return newsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(news_);
        }
      }
      public com.idamobile.protocol.ubrr.News.NewsMessage.Builder addNewsBuilder() {
        return getNewsFieldBuilder().addBuilder(
            com.idamobile.protocol.ubrr.News.NewsMessage.getDefaultInstance());
      }
      public com.idamobile.protocol.ubrr.News.NewsMessage.Builder addNewsBuilder(
          int index) {
        return getNewsFieldBuilder().addBuilder(
            index, com.idamobile.protocol.ubrr.News.NewsMessage.getDefaultInstance());
      }
      public java.util.List<com.idamobile.protocol.ubrr.News.NewsMessage.Builder> 
           getNewsBuilderList() {
        return getNewsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.idamobile.protocol.ubrr.News.NewsMessage, com.idamobile.protocol.ubrr.News.NewsMessage.Builder, com.idamobile.protocol.ubrr.News.NewsMessageOrBuilder> 
          getNewsFieldBuilder() {
        if (newsBuilder_ == null) {
          newsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.idamobile.protocol.ubrr.News.NewsMessage, com.idamobile.protocol.ubrr.News.NewsMessage.Builder, com.idamobile.protocol.ubrr.News.NewsMessageOrBuilder>(
                  news_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          news_ = null;
        }
        return newsBuilder_;
      }
      
      // repeated int32 deletedIds = 2;
      private java.util.List<java.lang.Integer> deletedIds_ = java.util.Collections.emptyList();;
      private void ensureDeletedIdsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          deletedIds_ = new java.util.ArrayList<java.lang.Integer>(deletedIds_);
          bitField0_ |= 0x00000002;
         }
      }
      public java.util.List<java.lang.Integer>
          getDeletedIdsList() {
        return java.util.Collections.unmodifiableList(deletedIds_);
      }
      public int getDeletedIdsCount() {
        return deletedIds_.size();
      }
      public int getDeletedIds(int index) {
        return deletedIds_.get(index);
      }
      public Builder setDeletedIds(
          int index, int value) {
        ensureDeletedIdsIsMutable();
        deletedIds_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addDeletedIds(int value) {
        ensureDeletedIdsIsMutable();
        deletedIds_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllDeletedIds(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureDeletedIdsIsMutable();
        super.addAll(values, deletedIds_);
        onChanged();
        return this;
      }
      public Builder clearDeletedIds() {
        deletedIds_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:messaging.NewsResponse)
    }
    
    static {
      defaultInstance = new NewsResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:messaging.NewsResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messaging_NewsMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messaging_NewsMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messaging_NewsRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messaging_NewsRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messaging_NewsResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messaging_NewsResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nnews.proto\022\tmessaging\"n\n\013NewsMessage\022\n" +
      "\n\002id\030\001 \002(\005\022\r\n\005title\030\002 \002(\t\022\017\n\007preview\030\003 \001" +
      "(\t\022\013\n\003url\030\004 \001(\t\022\020\n\010htmlBody\030\005 \001(\t\022\024\n\014cre" +
      "ationDate\030\006 \001(\003\"\036\n\013NewsRequest\022\017\n\007newsId" +
      "s\030\001 \003(\005\"H\n\014NewsResponse\022$\n\004news\030\001 \003(\0132\026." +
      "messaging.NewsMessage\022\022\n\ndeletedIds\030\002 \003(" +
      "\005B\035\n\033com.idamobile.protocol.ubrr"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_messaging_NewsMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_messaging_NewsMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messaging_NewsMessage_descriptor,
              new java.lang.String[] { "Id", "Title", "Preview", "Url", "HtmlBody", "CreationDate", },
              com.idamobile.protocol.ubrr.News.NewsMessage.class,
              com.idamobile.protocol.ubrr.News.NewsMessage.Builder.class);
          internal_static_messaging_NewsRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_messaging_NewsRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messaging_NewsRequest_descriptor,
              new java.lang.String[] { "NewsIds", },
              com.idamobile.protocol.ubrr.News.NewsRequest.class,
              com.idamobile.protocol.ubrr.News.NewsRequest.Builder.class);
          internal_static_messaging_NewsResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_messaging_NewsResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messaging_NewsResponse_descriptor,
              new java.lang.String[] { "News", "DeletedIds", },
              com.idamobile.protocol.ubrr.News.NewsResponse.class,
              com.idamobile.protocol.ubrr.News.NewsResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
